Create procedure Etutumuz
as
Select ID,DERSAD,(TBLOGRETMEN.AD+' '+TBLOGRENCI.SOYAD) as 'Öðretmen',(TBLOGRENCI.AD+' '+TBLOGRENCI.SOYAD) as 'Öðrenci',TARIH,SAAT,DURUM
From TBLETUT

inner join TBLDERSLER
on
TBLETUT.DERSID=TBLDERSLER.DERSID

inner join TBLOGRETMEN
on
TBLETUT.OGRETMENID=TBLOGRETMEN.OGRTID

inner join TBLOGRENCI
on
TBLETUT.OGRENCIID=TBLOGRENCI.OGRID